# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a =  np.random.randint(10,90,(2,3,5)) # random numpy array of shape (4,5)

print(a.shape)

(2, 3, 5)


In [8]:
# Method 2
a = np.random.randn(2,3,5)
print(a.shape)

(2, 3, 5)


In [9]:
# Method 3
a = np.random.rand(2,3,5)
print(a.shape)

(2, 3, 5)


#### 4. Print *a*.


In [10]:
# your code here
print(a)

[[[0.12423493 0.33007054 0.12690177 0.47661309 0.80979352]
  [0.19545267 0.28594212 0.09999177 0.92721991 0.92426209]
  [0.0123477  0.27514944 0.11817712 0.46592904 0.75083052]]

 [[0.01829076 0.51025015 0.13557564 0.56587495 0.96480563]
  [0.10647177 0.77148566 0.88442725 0.39530676 0.03748185]
  [0.31765546 0.0476422  0.82363349 0.73764808 0.40789917]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b = np.ones(shape=(5,2,3))


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [ ]:
# your code here
print(b)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

They do not have the same size because the shape (2 i,3 j,5 k) is not the same as the shape of b (5 i,2 j, 3k)

In [13]:
# your code here
print(f"Shape of a = {a.shape}")
print(f"Shape of b = {b.shape}")


Shape of a = (2, 3, 5)
Shape of b = (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In order to add a and b, the dimensions of the matrix a should be equal to the matrix b dimensions. The order of both matrices should be equal
i.e. $ A+B = [a_{ij}] + [b_{ij}] = [a_{ij} + b_{ij}]$

In [14]:
# your answer here
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
# your code here
c = b.reshape(2,3,5)
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

It works because the order of matrices are the same ( same number of rows, columns)

In [17]:
# your code/answer here
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [18]:
# your code/answer here
print(a)

[[[0.12423493 0.33007054 0.12690177 0.47661309 0.80979352]
  [0.19545267 0.28594212 0.09999177 0.92721991 0.92426209]
  [0.0123477  0.27514944 0.11817712 0.46592904 0.75083052]]

 [[0.01829076 0.51025015 0.13557564 0.56587495 0.96480563]
  [0.10647177 0.77148566 0.88442725 0.39530676 0.03748185]
  [0.31765546 0.0476422  0.82363349 0.73764808 0.40789917]]]


The shape of a is (2,3,5) which means that it is an array (tensor) composed of 2 "layers" of matrices composed of 3 rows and 5 columns

In [20]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


The shape of a is (5,2,3) which means that it is an array (tensor) composed of 5 "layers" of matrices composed of 2 rows and 3 columns

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
# your code here
e = np.multiply(a,c)
print(e.shape)

(2, 3, 5)


#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
# your code/answer here
print(a)
print(e)

[[[0.12423493 0.33007054 0.12690177 0.47661309 0.80979352]
  [0.19545267 0.28594212 0.09999177 0.92721991 0.92426209]
  [0.0123477  0.27514944 0.11817712 0.46592904 0.75083052]]

 [[0.01829076 0.51025015 0.13557564 0.56587495 0.96480563]
  [0.10647177 0.77148566 0.88442725 0.39530676 0.03748185]
  [0.31765546 0.0476422  0.82363349 0.73764808 0.40789917]]]
[[[0.12423493 0.33007054 0.12690177 0.47661309 0.80979352]
  [0.19545267 0.28594212 0.09999177 0.92721991 0.92426209]
  [0.0123477  0.27514944 0.11817712 0.46592904 0.75083052]]

 [[0.01829076 0.51025015 0.13557564 0.56587495 0.96480563]
  [0.10647177 0.77148566 0.88442725 0.39530676 0.03748185]
  [0.31765546 0.0476422  0.82363349 0.73764808 0.40789917]]]


$e$ is the same as $a$ because $c$ is composed of only values = 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [53]:
# your code here
d_max = np.max(d); print(d_max)
# your code here
d_min = np.min(d); print(d_min)
# your code here
d_mean = np.mean(d); print(d_mean)

1.964805629485578
1.0123477003862829
1.4215788345301352


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [48]:
# your code here
f = np.empty(shape=(2,3,5))
print(f)
print("\n")
print(d)

[[[1.12423493 1.33007054 1.12690177 1.47661309 1.80979352]
  [1.19545267 1.28594212 1.09999177 1.92721991 1.92426209]
  [1.0123477  1.27514944 1.11817712 1.46592904 1.75083052]]

 [[1.01829076 1.51025015 1.13557564 1.56587495 1.96480563]
  [1.10647177 1.77148566 1.88442725 1.39530676 1.03748185]
  [1.31765546 1.0476422  1.82363349 1.73764808 1.40789917]]]


[[[1.12423493 1.33007054 1.12690177 1.47661309 1.80979352]
  [1.19545267 1.28594212 1.09999177 1.92721991 1.92426209]
  [1.0123477  1.27514944 1.11817712 1.46592904 1.75083052]]

 [[1.01829076 1.51025015 1.13557564 1.56587495 1.96480563]
  [1.10647177 1.77148566 1.88442725 1.39530676 1.03748185]
  [1.31765546 1.0476422  1.82363349 1.73764808 1.40789917]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [50]:
f[np.where((d_min<d) & (d<d_mean))] = 25
f[np.where((d_mean<d) & (d<d_max))] = 75
f[np.where(d==d_mean)] = 50
f[np.where(d==d_min)] = 0
f[np.where(d==d_max)] = 100

In [51]:
print(f)

[[[ 25.  25.  25.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [  0.  25.  25.  75.  75.]]

 [[ 25.  75.  25.  75. 100.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]]]


In [52]:
print(d)

[[[1.12423493 1.33007054 1.12690177 1.47661309 1.80979352]
  [1.19545267 1.28594212 1.09999177 1.92721991 1.92426209]
  [1.0123477  1.27514944 1.11817712 1.46592904 1.75083052]]

 [[1.01829076 1.51025015 1.13557564 1.56587495 1.96480563]
  [1.10647177 1.77148566 1.88442725 1.39530676 1.03748185]
  [1.31765546 1.0476422  1.82363349 1.73764808 1.40789917]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [54]:
# your code here
print(f)
print(d)

[[[ 25.  25.  25.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [  0.  25.  25.  75.  75.]]

 [[ 25.  75.  25.  75. 100.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]]]
[[[1.12423493 1.33007054 1.12690177 1.47661309 1.80979352]
  [1.19545267 1.28594212 1.09999177 1.92721991 1.92426209]
  [1.0123477  1.27514944 1.11817712 1.46592904 1.75083052]]

 [[1.01829076 1.51025015 1.13557564 1.56587495 1.96480563]
  [1.10647177 1.77148566 1.88442725 1.39530676 1.03748185]
  [1.31765546 1.0476422  1.82363349 1.73764808 1.40789917]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [59]:
# your code here
g = np.empty(shape=(2,3,5))
g =g.astype('U256')
print(g)
print(d)

[[['1.124234934629539' '1.3300705423115216' '1.1269017706181876'
   '1.476613087440671' '1.8097935241739453']
  ['1.195452672489011' '1.285942115555105' '1.0999917650171476'
   '1.9272199059319117' '1.9242620879948182']
  ['1.0123477003862829' '1.2751494350903014' '1.118177115467863'
   '1.4659290390991337' '1.7508305207096935']]

 [['1.0182907613890015' '1.5102501503275811' '1.1355756374701405'
   '1.5658749502630172' '1.964805629485578']
  ['1.1064717685256205' '1.7714856579416562' '1.8844272544970075'
   '1.395306758009513' '1.0374818539377402']
  ['1.3176554618817429' '1.0476421974869268' '1.8236334903979954'
   '1.7376480784931594' '1.407899168882247']]]
[[[1.12423493 1.33007054 1.12690177 1.47661309 1.80979352]
  [1.19545267 1.28594212 1.09999177 1.92721991 1.92426209]
  [1.0123477  1.27514944 1.11817712 1.46592904 1.75083052]]

 [[1.01829076 1.51025015 1.13557564 1.56587495 1.96480563]
  [1.10647177 1.77148566 1.88442725 1.39530676 1.03748185]
  [1.31765546 1.0476422  1.82363349

In [60]:
g[np.where((d_min<d) & (d<d_mean))] = "B"
g[np.where((d_mean<d) & (d<d_max))] = "C"
g[np.where(d==d_mean)] = "D"
g[np.where(d==d_min)] = "A"
g[np.where(d==d_max)] = "E"

In [61]:
print(g)

[[['B' 'B' 'B' 'C' 'C']
  ['B' 'B' 'B' 'C' 'C']
  ['A' 'B' 'B' 'C' 'C']]

 [['B' 'C' 'B' 'C' 'E']
  ['B' 'C' 'C' 'B' 'B']
  ['B' 'B' 'C' 'C' 'B']]]
